[workspace]
resolver = "2"

members = ["btreeprint", "json_verify", "nocommit", "xtask"]

[workspace.dependencies]
ahash = "0.8.7"
clap = "4.4.18"
color-eyre = "0.6.2"
colored = "2.1.0"
fs-err = "2.11.0"
git2 = "0.18.1"
ignore = "0.4.22"
indicatif = "0.17.7"
itertools = "0.12.0"
serde = "1.0.195"
serde_json = "1.0.111"
strum = "0.26.1"
termtree = "0.4.1"
thiserror = "1.0.56"
tracing = "0.1.40"
tracing-error = "0.2.0"
tracing-subscriber = "0.3.18"
walkdir = "2.4.0"

[profile.release]
opt-level = 3
codegen-units = 1
lto = true
strip = true

# Enable a small amount of optimization in debug mode
[profile.dev]
lto = "off"
opt-level = 1

# Enable high optimizations for dependencies
[profile.dev.package."*"]
opt-level = 2
